# Site settings
title: Spyros Poulos
description: This is my Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Poulos Spyros
user_description: I am an experienced data scientist with experience on managing large scale teams and projects. I love teaching corporate trainings and individuals
user_title: Head of BI and Data Analytics
email: mauriurraco@gmail.com
# twitter_username: lorem_ipsum
instagram_username: spyros_poulos
facebook_username: spyros.poulos.5
linkedin_username: spyros-poulos
github_username:  spyr85
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

